"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function AdminLoginPage(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");setLoading(true);try{const r=await fetch("/api/auth/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){setError(d.error??"Unable to sign in.");return;}router.replace("/admin");router.refresh();}catch{setError("Admin service is unavailable.")}finally{setLoading(false);}}
 return <main className="min-h-screen bg-background flex items-center justify-center px-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-border bg-surface p-7"><p className="text-[9px] uppercase tracking-[0.2em] text-primary">FORMA / ADMIN</p><h1 className="mt-2 font-serif text-4xl">Admin sign in</h1><label className="mt-6 block text-xs text-muted">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm text-foreground"/></label><label className="mt-4 block text-xs text-muted">Admin password<input required minLength={12} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm text-foreground"/></label>{error&&<p className="mt-4 text-xs text-red-300">{error}</p>}<button disabled={loading} className="mt-6 h-11 w-full rounded-xl bg-primary text-sm font-semibold text-primary-foreground">{loading?"Signing in…":"Sign in"}</button></form></main>
}