"use client";
import { useEffect,useState } from 'react';
import { AdminPage,AdminCard,AdminButton,AdminTable,AdminTableHeader } from '@/components/admin/AdminKit';

type Product={id:string;name:string;slug:string;status:string;isFeatured:boolean;isTrending:boolean;category?:{name:string}|null;prices?:Array<{amountMinor:number}>};
export default function CatalogTools(){
 const [products,setProducts]=useState<Product[]>([]),[selected,setSelected]=useState<string[]>([]),[action,setAction]=useState(''),[message,setMessage]=useState(''),[csv,setCsv]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/catalog',{cache:'no-store'});if(r.ok)setProducts((await r.json()).products??[])}finally{setLoading(false)}} useEffect(()=>{void load()},[]);
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 async function bulk(){if(!selected.length||!action)return;setMessage('');const r=await fetch('/api/admin/products/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected,action})});const d=await r.json().catch(()=>null);setMessage(r.ok?'Updated '+(d?.updated??0)+' products.':(d?.message||'Bulk action failed.'));if(r.ok){setSelected([]);await load()}}
 function exportCsv(){const headers=['name','slug','status','isFeatured','isTrending','category','price'];const rows=products.map(p=>[p.name,p.slug,p.status,String(p.isFeatured),String(p.isTrending),p.category?.name??'',String((p.prices?.[0]?.amountMinor??0)/100)]);const esc=(v:string)=>'"'+v.replaceAll('"','""')+'"';const text=[headers,...rows].map(row=>row.map(esc).join(',')).join('\n');const blob=new Blob([text],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='products.csv';a.click();URL.revokeObjectURL(url)}
 async function importCsv(){if(!csv.trim())return;const r=await fetch('/api/admin/products/import-csv',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv})});const d=await r.json().catch(()=>null);setMessage(r.ok?'Imported: '+(d?.created??0)+' created, '+(d?.updated??0)+' updated, '+(d?.errors?.length??0)+' errors.':(d?.message||'Import failed.'));if(r.ok){setCsv('');await load()}}
 async function duplicate(id:string){const r=await fetch('/api/admin/products/duplicate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:id})});const d=await r.json().catch(()=>null);setMessage(r.ok?'Draft duplicate created: '+d.name:(d?.message||'Duplicate failed.'));if(r.ok)await load()}
 return <AdminPage title="Catalog operations" eyebrow="Catalog" description="Bulk product actions, safe duplication, and CSV import/export." actions={<div className="flex gap-2"><AdminButton onClick={exportCsv}>Export CSV</AdminButton><AdminButton onClick={()=>document.getElementById('csv-file')?.click()}>Import CSV</AdminButton><input id="csv-file" type="file" accept=".csv,text/csv" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(f)setCsv(await f.text())}}/></div>}>
 <AdminCard className="mt-7"><div className="flex flex-wrap items-center gap-2"><select value={action} onChange={e=>setAction(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-xs"><option value="">Bulk action…</option><option value="ACTIVATE">Activate</option><option value="ARCHIVE">Archive</option><option value="FEATURE">Feature</option><option value="UNFEATURE">Unfeature</option><option value="TRENDING">Mark trending</option><option value="UNTRENDING">Remove trending</option></select><AdminButton disabled={!selected.length||!action} onClick={()=>void bulk()}>Apply to {selected.length||0}</AdminButton>{message&&<span className="text-xs text-muted">{message}</span>}</div><div className="mt-4"><textarea value={csv} onChange={e=>setCsv(e.target.value)} placeholder="CSV import preview / paste CSV here" className="min-h-24 w-full rounded-xl border border-border bg-background p-3 text-xs"/>{csv&&<div className="mt-2"><AdminButton onClick={()=>void importCsv()}>Process CSV</AdminButton></div>}</div></AdminCard>
 <AdminCard className="mt-5"><AdminTable><AdminTableHeader><th className="p-3"><input type="checkbox" checked={products.length>0&&selected.length===products.length} onChange={e=>setSelected(e.target.checked?products.map(p=>p.id):[])}/></th><th className="p-3">Product</th><th className="p-3">Status</th><th className="p-3">Category</th><th className="p-3">Actions</th></AdminTableHeader><tbody>{loading?<tr><td colSpan={5} className="p-5">Loading…</td></tr>:products.map(p=><tr key={p.id} className="border-b border-border last:border-0"><td className="p-3"><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/></td><td className="p-3"><div>{p.name}</div><div className="text-[10px] text-muted">{p.slug}</div></td><td className="p-3">{p.status}</td><td className="p-3 text-muted">{p.category?.name??'—'}</td><td className="p-3"><AdminButton onClick={()=>void duplicate(p.id)}>Duplicate</AdminButton></td></tr>)}</tbody></AdminTable></AdminCard>
 </AdminPage>}
