"use client";
import { useEffect, useState } from "react";
import { IconBan, IconCheck, IconRefresh, IconSearch, IconUser } from "@tabler/icons-react";
type Customer={id:string;name:string|null;email:string;phone:string|null;isActive:boolean;createdAt:string;_count:{orders:number;customRequests:number;wishlist:number}};
export default function Customers(){
const [rows,setRows]=useState<Customer[]>([]); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null);
async function load(){setLoading(true);try{const q=search.trim()?"?search="+encodeURIComponent(search.trim()):"";const r=await fetch("/api/admin/customers"+q,{cache:"no-store"});if(!r.ok)throw new Error();setRows(await r.json())}finally{setLoading(false)}}
useEffect(()=>{const t=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(t)},[search]);
async function toggle(c:Customer){setBusy(c.id);try{const r=await fetch("/api/admin/customers/"+c.id+"/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!c.isActive})});if(!r.ok)throw new Error();await load()}finally{setBusy(null)}}
return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[0.2em] text-primary">Customers</p><h1 className="mt-2 font-serif text-4xl">Customer management</h1><p className="mt-2 text-sm text-muted">Search customers, review activity and control account access.</p></div><button onClick={()=>void load()} className="rounded-xl border border-border p-2 text-muted"><IconRefresh size={16}/></button></div>
<div className="mt-6 flex items-center gap-2 rounded-xl border border-border bg-surface px-3"><IconSearch size={15} className="text-muted"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email or phone…" className="h-10 flex-1 bg-transparent text-xs outline-none"/></div>
<div className="mt-5 space-y-3">{loading?[1,2,3].map(i=><div key={i} className="h-28 animate-pulse rounded-2xl bg-surface"/>):rows.map(c=><article key={c.id} className="rounded-2xl border border-border bg-surface p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary"><IconUser size={17}/></div><div className="min-w-0"><p className="truncate text-sm font-medium">{c.name||"Unnamed customer"}</p><p className="truncate text-xs text-muted">{c.email}{c.phone?" · "+c.phone:""}</p></div></div><button onClick={()=>void toggle(c)} disabled={busy===c.id} className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-[10px] disabled:opacity-50">{c.isActive?<><IconBan size={14}/> Disable</>:<><IconCheck size={14}/> Enable</>}</button></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-background p-2"><p className="text-[9px] text-muted">Orders</p><p className="mt-1 text-sm font-semibold">{c._count.orders}</p></div><div className="rounded-xl bg-background p-2"><p className="text-[9px] text-muted">Custom</p><p className="mt-1 text-sm font-semibold">{c._count.customRequests}</p></div><div className="rounded-xl bg-background p-2"><p className="text-[9px] text-muted">Wishlist</p><p className="mt-1 text-sm font-semibold">{c._count.wishlist}</p></div></div></article>)}{!loading&&!rows.length&&<div className="rounded-2xl border border-dashed border-border p-10 text-sm text-muted">No customers found.</div>}</div></main>
}