import {getDiscoveryFallbackCategory} from "@/config/shop-categories";
import {getBackendApiUrl} from "@/lib/backend-api";
import {mapCatalogProducts,type CatalogProduct} from "@/lib/catalog-api";
import {SHOP_PAGE_SIZE,type ShopQueryState} from "@/lib/shop-query";
export interface ShopPageResult{items:ReturnType<typeof mapCatalogProducts>;total:number;page:number;pageSize:number;totalPages:number;fallbackFor?:string}
const categoryIdToName:Record<string,string>={gaming:"Gaming",anime:"Anime","desk-toys":"Desk Toys","kids-toys":"Desk Toys",custom:"Custom",heroes:"Heroes",props:"Weapon Props",display:"Display",collectibles:"Collectibles","mobile-tv":"Mobile / TV"};
interface ShopPageResponse{items:CatalogProduct[];total:number;page:number;pageSize:number;totalPages:number}
async function request(s:ShopQueryState,names:string[],q:string){const p=new URLSearchParams({page:String(s.page),limit:String(SHOP_PAGE_SIZE),sort:s.sort});if(q)p.set("q",q);if(names.length)p.set("category",names.join(","));if(s.minPrice>0)p.set("minPrice",String(s.minPrice));if(Number.isFinite(s.maxPrice))p.set("maxPrice",String(s.maxPrice));if(s.minRating>0)p.set("minRating",String(s.minRating));const r=await fetch(getBackendApiUrl("products/shop?"+p.toString()),{next:{revalidate:60}});if(!r.ok)throw new Error("Shop request failed with "+r.status);return await r.json() as ShopPageResponse}
export async function fetchShopPage(s:ShopQueryState,lockedCategory?:string):Promise<ShopPageResult|null>{const names=lockedCategory?[lockedCategory]:s.categories.map(id=>categoryIdToName[id]??id);try{let d=await request(s,names,s.q.trim());let fallbackFor:string|undefined;if(d.total===0&&s.q.trim()){const fallback=getDiscoveryFallbackCategory(s.q.trim().toLowerCase());const name=fallback?categoryIdToName[fallback.id]:undefined;if(name){d=await request(s,[name],"");if(d.total>0)fallbackFor=s.q.trim()}}return{items:mapCatalogProducts(d.items??[]),total:d.total,page:d.page,pageSize:d.pageSize,totalPages:d.totalPages,fallbackFor}}catch{return null}}
