"use client";
import { useEffect, useState } from "react";
import { IconDeviceFloppy, IconInfoCircle } from "@tabler/icons-react";
type Featured={id:string;name:string;slug:string};
export default function StoreControls(){
const [featured,setFeatured]=useState<Featured[]>([]); const [limit,setLimit]=useState("6"); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
async function load(){const r=await fetch("/api/admin/settings",{cache:"no-store"});if(!r.ok)return;const d=await r.json();const h=d.settings?.hero;if(h?.maxItems)setLimit(String(h.maxItems));if(Array.isArray(d.featured))setFeatured(d.featured)}
useEffect(()=>{void load()},[]);
async function save(){setSaving(true);setMessage("");try{const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({hero:{maxItems:Number(limit)}})});if(!r.ok)throw new Error();setMessage("Hero settings saved.")}catch{setMessage("Unable to save hero settings.")}finally{setSaving(false)}}
return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-[9px] uppercase tracking-[0.2em] text-primary">Storefront</p><h1 className="mt-2 font-serif text-4xl">Store controls</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Hero products are manually curated. Bestsellers and new arrivals are calculated automatically from live catalog data.</p>
<section className="mt-7 rounded-2xl border border-border bg-surface p-5"><div className="flex items-start gap-3"><IconInfoCircle size={17} className="mt-0.5 text-primary"/><div><p className="text-xs font-semibold">Hero configuration</p><p className="mt-1 text-[10px] leading-5 text-muted">Feature products from Catalog to place them in the hero carousel. This setting controls how many featured products the hero may display.</p></div></div><label className="mt-5 block max-w-xs text-[10px] text-muted">Maximum hero products<input value={limit} onChange={e=>setLimit(e.target.value)} type="number" min="1" max="12" className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm text-foreground"/></label><button onClick={()=>void save()} disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-foreground px-4 py-2.5 text-xs font-semibold text-background"><IconDeviceFloppy size={15}/>{saving?"Saving…":"Save"}</button>{message&&<p className="mt-3 text-xs text-muted">{message}</p>}</section>
<section className="mt-5 rounded-2xl border border-border bg-surface p-5"><p className="text-xs font-semibold">Currently featured</p><p className="mt-1 text-[10px] text-muted">Use Catalog to feature or unfeature products.</p><div className="mt-4 space-y-2">{featured.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl border border-border p-3"><span className="text-xs">{p.name}</span><span className="rounded-full bg-primary/10 px-2 py-1 text-[9px] text-primary">Hero</span></div>)}{!featured.length&&<p className="py-5 text-xs text-muted">No products are featured yet.</p>}</div></section>
<section className="mt-5 rounded-2xl border border-border bg-surface p-5"><p className="text-xs font-semibold">Automatic merchandising</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-border p-4"><p className="text-[9px] uppercase tracking-[0.12em] text-muted">Bestseller</p><p className="mt-2 text-sm">Units sold + purchases + cart adds + views</p></div><div className="rounded-xl border border-border p-4"><p className="text-[9px] uppercase tracking-[0.12em] text-muted">New arrivals</p><p className="mt-2 text-sm">Newest active products by creation date</p></div></div></section>
</main>
}