"use client";
import { useEffect,useState } from 'react';
import { AdminPage,AdminCard,AdminTable,AdminTableHeader,AdminButton } from '@/components/admin/AdminKit';

type Job={id:string;status:string;attempts:number;maxAttempts:number;errorMessage?:string|null;createdAt:string;startedAt?:string|null;completedAt?:string|null;productFile?:{originalName:string;processingStatus:string}|null;outputFile?:{originalName:string}|null};
export default function ProcessingPage(){const [jobs,setJobs]=useState<Job[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');
 async function load(){setLoading(true);try{const r=await fetch('/api/processing-jobs',{cache:'no-store'});if(r.ok)setJobs(await r.json())}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function retry(id:string){setBusy(id);try{await fetch('/api/processing-jobs/'+id+'/retry',{method:'POST'});await load()}finally{setBusy('')}}
 async function run(){setBusy('run');try{await fetch('/api/processing-jobs/worker/run',{method:'POST'});await load()}finally{setBusy('')}}
 return <AdminPage title="3D processing" eyebrow="Operations" description="Monitor conversion jobs, retries and failed 3D assets." actions={<AdminButton onClick={()=>void run()} disabled={busy==='run'}>{busy==='run'?'Running…':'Run next job'}</AdminButton>}><AdminCard className="mt-7"><AdminTable><AdminTableHeader><th className="p-3">File</th><th className="p-3">Status</th><th className="p-3">Attempts</th><th className="p-3">Created</th><th className="p-3">Error</th><th className="p-3">Action</th></AdminTableHeader><tbody>{loading?<tr><td colSpan={6} className="p-5 text-muted">Loading…</td></tr>:jobs.map(j=><tr key={j.id} className="border-b border-border last:border-0"><td className="p-3">{j.productFile?.originalName??j.id}</td><td className="p-3">{j.status}</td><td className="p-3">{j.attempts}/{j.maxAttempts}</td><td className="p-3">{new Date(j.createdAt).toLocaleString()}</td><td className="max-w-md p-3 text-muted">{j.errorMessage??'—'}</td><td className="p-3">{j.status==='FAILED'&&<AdminButton onClick={()=>void retry(j.id)} disabled={busy===j.id}>{busy===j.id?'Retrying…':'Retry'}</AdminButton>}</td></tr>)}</tbody></AdminTable></AdminCard></AdminPage>}
